use portal;

INSERT INTO portal.transmissiontypes (transmission) VALUES ('Manuális');
INSERT INTO portal.transmissiontypes (transmission) VALUES ('Automata');
INSERT INTO portal.transmissiontypes (transmission) VALUES ('Fokozatmentes automata');
INSERT INTO portal.transmissiontypes (transmission) VALUES ('Robotizált váltó');

INSERT INTO portal.fueltypes (fuel) VALUES ("Benzin");
INSERT INTO portal.fueltypes (fuel) VALUES ("Dízel");
INSERT INTO portal.fueltypes (fuel) VALUES ("LPG");
INSERT INTO portal.fueltypes (fuel) VALUES ("CNG");
INSERT INTO portal.fueltypes (fuel) VALUES ("Hibrid (Benzin)");
INSERT INTO portal.fueltypes (fuel) VALUES ("Hibrid (Dízel)");
INSERT INTO portal.fueltypes (fuel) VALUES ("Elektromos");
INSERT INTO portal.fueltypes (fuel) VALUES ("Hidrogén");

INSERT INTO portal.drivetypes (drive) VALUES ("Elsőkerék meghajtás");
INSERT INTO portal.drivetypes (drive) VALUES ("Hátsókerék meghajtás");
INSERT INTO portal.drivetypes (drive) VALUES ("Kapcsolható összkereék meghajtás");
INSERT INTO portal.drivetypes (drive) VALUES ("Állandó összkereék meghajtás");

INSERT INTO portal.bodytypes (body) VALUES ("Szedán");
INSERT INTO portal.bodytypes (body) VALUES ("Kombi");
INSERT INTO portal.bodytypes (body) VALUES ("Ferdehátú");
INSERT INTO portal.bodytypes (body) VALUES ("Kabrio");
INSERT INTO portal.bodytypes (body) VALUES ("Egyterű");
INSERT INTO portal.bodytypes (body) VALUES ("Cupe");
INSERT INTO portal.bodytypes (body) VALUES ("SUV");
INSERT INTO portal.bodytypes (body) VALUES ("Kisbusz");
INSERT INTO portal.bodytypes (body) VALUES ("Sport");
INSERT INTO portal.bodytypes (body) VALUES ("Pickup");
INSERT INTO portal.bodytypes (body) VALUES ("Terepjáró");
INSERT INTO portal.bodytypes (body) VALUES ("Egyéb");

INSERT INTO portal.vehiclecategories (category) VALUES ("Személygépjármű");
INSERT INTO portal.vehiclecategories (category) VALUES ("Kishaszonjármű");
INSERT INTO portal.vehiclecategories (category) VALUES ("Haszonjármű");
INSERT INTO portal.vehiclecategories (category) VALUES ("Munkagép");

INSERT INTO portal.vehiclemakes (make) VALUES ("Acura");
INSERT INTO portal.vehiclemakes (make) VALUES ("Alfa Romeo");
INSERT INTO portal.vehiclemakes (make) VALUES ("Alpina");
INSERT INTO portal.vehiclemakes (make) VALUES ("Aston Martin");
INSERT INTO portal.vehiclemakes (make) VALUES ("Audi");
INSERT INTO portal.vehiclemakes (make) VALUES ("Bentley");
INSERT INTO portal.vehiclemakes (make) VALUES ("BMW");
INSERT INTO portal.vehiclemakes (make) VALUES ("Bugatti");
INSERT INTO portal.vehiclemakes (make) VALUES ("Cadilac");
INSERT INTO portal.vehiclemakes (make) VALUES ("Chevrolet");
INSERT INTO portal.vehiclemakes (make) VALUES ("Chrysles");
INSERT INTO portal.vehiclemakes (make) VALUES ("Citroen");
INSERT INTO portal.vehiclemakes (make) VALUES ("Cupra");
INSERT INTO portal.vehiclemakes (make) VALUES ("Dacia");
INSERT INTO portal.vehiclemakes (make) VALUES ("Daewoo");
INSERT INTO portal.vehiclemakes (make) VALUES ("Daihatsu");
INSERT INTO portal.vehiclemakes (make) VALUES ("Dodge");
INSERT INTO portal.vehiclemakes (make) VALUES ("DS");
INSERT INTO portal.vehiclemakes (make) VALUES ("Ferrari");
INSERT INTO portal.vehiclemakes (make) VALUES ("Fiat");
INSERT INTO portal.vehiclemakes (make) VALUES ("Ford");
INSERT INTO portal.vehiclemakes (make) VALUES ("Genesis");
INSERT INTO portal.vehiclemakes (make) VALUES ("GMC");
INSERT INTO portal.vehiclemakes (make) VALUES ("Great Wall");
INSERT INTO portal.vehiclemakes (make) VALUES ("Haval");
INSERT INTO portal.vehiclemakes (make) VALUES ("Honda");
INSERT INTO portal.vehiclemakes (make) VALUES ("Hummer");
INSERT INTO portal.vehiclemakes (make) VALUES ("Hyundai");
INSERT INTO portal.vehiclemakes (make) VALUES ("Infiniti");
INSERT INTO portal.vehiclemakes (make) VALUES ("Jaguar");
INSERT INTO portal.vehiclemakes (make) VALUES ("Jeep");
INSERT INTO portal.vehiclemakes (make) VALUES ("Kia");
INSERT INTO portal.vehiclemakes (make) VALUES ("Koenigsegg");
INSERT INTO portal.vehiclemakes (make) VALUES ("Lada");
INSERT INTO portal.vehiclemakes (make) VALUES ("Lamborghini");
INSERT INTO portal.vehiclemakes (make) VALUES ("Lancia");
INSERT INTO portal.vehiclemakes (make) VALUES ("Land Rover");
INSERT INTO portal.vehiclemakes (make) VALUES ("Lexus");
INSERT INTO portal.vehiclemakes (make) VALUES ("Lotus");
INSERT INTO portal.vehiclemakes (make) VALUES ("Maserati");
INSERT INTO portal.vehiclemakes (make) VALUES ("Mazda");
INSERT INTO portal.vehiclemakes (make) VALUES ("McLaren");
INSERT INTO portal.vehiclemakes (make) VALUES ("Mercedes-Benz");
INSERT INTO portal.vehiclemakes (make) VALUES ("MG");
INSERT INTO portal.vehiclemakes (make) VALUES ("Mini");
INSERT INTO portal.vehiclemakes (make) VALUES ("Mitsubishi");
INSERT INTO portal.vehiclemakes (make) VALUES ("NIO");
INSERT INTO portal.vehiclemakes (make) VALUES ("Nissan");
INSERT INTO portal.vehiclemakes (make) VALUES ("Opel");
INSERT INTO portal.vehiclemakes (make) VALUES ("Peugeot");
INSERT INTO portal.vehiclemakes (make) VALUES ("Pegani");
INSERT INTO portal.vehiclemakes (make) VALUES ("Peugeot");
INSERT INTO portal.vehiclemakes (make) VALUES ("Porsche");
INSERT INTO portal.vehiclemakes (make) VALUES ("RAM");
INSERT INTO portal.vehiclemakes (make) VALUES ("Renault");
INSERT INTO portal.vehiclemakes (make) VALUES ("Rolls-Royce");
INSERT INTO portal.vehiclemakes (make) VALUES ("Rover");
INSERT INTO portal.vehiclemakes (make) VALUES ("Saab");
INSERT INTO portal.vehiclemakes (make) VALUES ("Seat");
INSERT INTO portal.vehiclemakes (make) VALUES ("Skoda");
INSERT INTO portal.vehiclemakes (make) VALUES ("Smart");
INSERT INTO portal.vehiclemakes (make) VALUES ("Subaru");
INSERT INTO portal.vehiclemakes (make) VALUES ("Suzuki");
INSERT INTO portal.vehiclemakes (make) VALUES ("Tesla");
INSERT INTO portal.vehiclemakes (make) VALUES ("Toyota");
INSERT INTO portal.vehiclemakes (make) VALUES ("Vauxhall");
INSERT INTO portal.vehiclemakes (make) VALUES ("Volkswagen");
INSERT INTO portal.vehiclemakes (make) VALUES ("Volvo");

INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("50", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("80", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("90", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("100", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("200", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("5000", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("A1", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("A2", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("A3", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("A4", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("A5", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("A6", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("A7", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("A8", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("e-tron", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("Q2", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("Q3", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("Q4 e-tron", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("Q5", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("Q7", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("Q8", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("Q8 ee-tron", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("Quattro", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("R8", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("RS 2", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("RS 3", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("RS 4", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("RS 5", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("RS 6", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("RS 7", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("RS e-tron GT", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("RS Q3", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("RS Q8", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("S1", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("S2", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("S3", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("S4", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("S5", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("S6", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("S7", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("S8", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("SQ2", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("SQ5", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("SQ8", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("SQ8 e-tron", "Audi", 1);
INSERT INTO portal.vehiclemodels (model, make, category) VALUES ("TT", "Audi", 1);